test fail action

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -21,16 +21,16 @@ jobs:
 
       - name: Wait for container to start
         run: |
-          for i in {1..4}; do
-            curl -s http://localhost:8080/api/report/system/health && break
+          for i in {1..2}; do
+            curl -s http://localhost:8000/api/report/system/health && break
             echo "Waiting for container to start... Attempt $i"
             sleep $((10 * i))
           done
-          curl -f http://localhost:8080/api/report/system/health || { echo "Container failed to start after attempts"; exit 1; }
+          curl -f http://localhost:8000/api/report/system/health || { echo "Container failed to start after attempts"; exit 1; }
 
       - name: Test APIs
         run: |
-          curl -f -o /dev/null -s -w "%{http_code}" http://localhost:8080/api/report/system/health | grep -q 200 || { echo "GET API failed"; exit 1; }
+          curl -f -o /dev/null -s -w "%{http_code}" http://localhost:8000/api/report/system/health | grep -q 200 || { echo "GET API failed"; exit 1; }
           curl -f -o /dev/null -s -w "%{http_code}" -X POST "http://localhost:8091?id=2024112100100043&timestamp=1749548226&lat=10.8195025&lon=106.6913659&speed=1.57&bearing=157.52&altitude=13.3&accuracy=18.63&batt=26" | grep -q 200 || { echo "POST API failed"; exit 1; }
 
       - name: Fail PR if build fails on non-main branch
